In [ ]:
import tensorflow as tf

t1 = tf.constant(tf.random.uniform(shape=[1500]),shape=[5,300])
t2 = tf.constant(tf.random.uniform(shape=[1500]),shape=[5,300])
t1,t2

(<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.8465384 , 0.5590538 , 0.7887471 , ..., 0.7462652 , 0.29600954,
         0.38576996],
        [0.71294534, 0.24151897, 0.27458942, ..., 0.6771095 , 0.388327  ,
         0.8589457 ],
        [0.9819313 , 0.84782183, 0.7302617 , ..., 0.55859375, 0.7088338 ,
         0.51334167],
        [0.35281897, 0.1451881 , 0.9660269 , ..., 0.6835108 , 0.02523851,
         0.987568  ],
        [0.39772558, 0.93134475, 0.6150187 , ..., 0.7796496 , 0.06061661,
         0.27029777]], dtype=float32)>,
 <tf.Tensor: shape=(5, 300), dtype=float32, numpy=
 array([[0.03561115, 0.12313855, 0.467471  , ..., 0.783944  , 0.15804279,
         0.76676226],
        [0.5365926 , 0.59959185, 0.7654253 , ..., 0.43441057, 0.8823999 ,
         0.53866255],
        [0.3986169 , 0.16396976, 0.33003867, ..., 0.8042897 , 0.96723187,
         0.81538785],
        [0.8932979 , 0.2633536 , 0.1320219 , ..., 0.08339691, 0.70732   ,
         0.46359253],
        [0.72188

In [ ]:
tf.matmul(t1,tf.transpose(t2))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.91239 , 75.73995 , 82.79645 , 78.57922 , 74.45244 ],
       [78.25995 , 73.6599  , 76.7549  , 72.91824 , 73.251434],
       [75.182816, 72.13531 , 73.20915 , 72.836006, 69.85535 ],
       [68.28856 , 66.07887 , 68.70693 , 63.151997, 61.80924 ],
       [75.864685, 73.748474, 76.225174, 71.66507 , 70.35848 ]],
      dtype=float32)>

In [ ]:
tf.tensordot(t1,tf.transpose(t2),axes=1)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[77.91239 , 75.73995 , 82.79645 , 78.57922 , 74.45244 ],
       [78.25995 , 73.6599  , 76.7549  , 72.91824 , 73.251434],
       [75.182816, 72.13531 , 73.20915 , 72.836006, 69.85535 ],
       [68.28856 , 66.07887 , 68.70693 , 63.151997, 61.80924 ],
       [75.864685, 73.748474, 76.225174, 71.66507 , 70.35848 ]],
      dtype=float32)>

In [ ]:
t3 = tf.constant(tf.random.uniform(shape=[150528]),shape=[224, 224, 3])
t3

<tf.Tensor: shape=(224, 224, 3), dtype=float32, numpy=
array([[[0.8399068 , 0.24864697, 0.20697975],
        [0.16662359, 0.24156773, 0.74830616],
        [0.7077117 , 0.2667451 , 0.1246599 ],
        ...,
        [0.98735344, 0.7507856 , 0.5617634 ],
        [0.9490123 , 0.27831852, 0.293108  ],
        [0.02180517, 0.959286  , 0.6956533 ]],

       [[0.34598756, 0.21227074, 0.48603833],
        [0.50823665, 0.42053497, 0.10821807],
        [0.9637265 , 0.05716598, 0.3961599 ],
        ...,
        [0.10327911, 0.8800757 , 0.36723804],
        [0.9968817 , 0.5980835 , 0.95995224],
        [0.36330545, 0.17266583, 0.99506986]],

       [[0.06027865, 0.37298524, 0.08140039],
        [0.83378184, 0.05473101, 0.26305223],
        [0.00256228, 0.32079268, 0.14828312],
        ...,
        [0.7807716 , 0.7353846 , 0.32628286],
        [0.7990935 , 0.66057837, 0.0714711 ],
        [0.27790964, 0.72430706, 0.07570493]],

       ...,

       [[0.1783024 , 0.7285936 , 0.8408239 ],
        [0.54

In [ ]:
tf.reduce_min(t3[:1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.00094747543>

In [ ]:
tf.reduce_max(t3[:1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.99877584>

In [ ]:
t4 = tf.constant(tf.random.uniform(shape=[150528]),shape=[1,224, 224, 3])
t4.shape, tf.squeeze(t4).shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

In [ ]:
t5 = tf.range(0,10)
tf.argmax(t5), tf.argmin(t5).numpy()

(<tf.Tensor: shape=(), dtype=int64, numpy=9>, 0)

In [ ]:
tf.one_hot(t5,depth=10)

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]], dtype=float32)>