### In this noutbook
,we`re gonna cover some of the most fundamental concepts of tensors using Tenserflow

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.14.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions in tensor (ndim stands fro number of dimension)
scalar.ndim

0

In [ ]:
# Create a vector
vector= tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of vecotor
vector.ndim

1

In [ ]:
# Create a matrix more than 1 dimension
matrix = tf.constant([[7,4],[4,7]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[7, 4],
       [4, 7]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix

another_matrix = tf.constant([[7.,4.],[4.,7.],[8.,16.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[ 7.,  4.],
       [ 4.,  7.],
       [ 8., 16.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
#Let`s create a tensor
tensor = tf.constant([[[14,58,93],[1,23,4]],[[4,4,5],[1,4,7]],[[7,32,1],[3,4,7]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[14, 58, 93],
        [ 1, 23,  4]],

       [[ 4,  4,  5],
        [ 1,  4,  7]],

       [[ 7, 32,  1],
        [ 3,  4,  7]]], dtype=int32)>

In [ ]:
tensor.ndim

3

Scalar: single number
Vector: number with direction (e.g wind speed and direction)
Matrix: a 2-dimensinal array of number
Tensor: n-dimensinal,0-dimensonal tensor is a scalar, a 1-dimensinal tensor is a vector

In [ ]:
# Create a same tensor with variable as above
changeable_tensor = tf.Variable([10,7])
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Creating ywo Random Tensors
random_1= tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(1,2))
random_2= tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,2))

random_1,random_2,random_1 == random_2


(<tf.Tensor: shape=(1, 2), dtype=float32, numpy=array([[-0.7565803 , -0.06854702]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193765, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [False, False],
        [False, False]])>)

In [ ]:
# Shuffle a tensor
not_shuffled= tf.constant([[10,7],[3,4],[5,6]])
#Start shuffle
tf.random.shuffle(not_shuffled)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 5,  6],
       [ 3,  4],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(102)
tf.random.shuffle(not_shuffled,seed=102)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 5,  6]], dtype=int32)>

In [ ]:
# Other way to create tensor all ones
tf.ones([9,3])

<tf.Tensor: shape=(9, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
# Other way to create tensor all ones
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

The main differance between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU

In [ ]:
import numpy as np
numpy_A= np.arange(1,25,dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,2,3,2))
A

<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]]], dtype=int32)>

###Getting information from tensors
* Shape
* Rank
* Axis of dimensions
* Size

In [ ]:
# Create rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[1][2][1][1]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions: ", rank_4_tensor.ndim)
print("Shape of tensor: ", rank_4_tensor.shape)
print("Element along the 0 axis: ", rank_4_tensor.shape[0])
print("Element along the last axis: ", rank_4_tensor.shape[-1])
print("Totall number of elements: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of tensor:  (2, 3, 4, 5)
Element along the 0 axis:  2
Element along the last axis:  5
Totall number of elements:  120


Tensor can be indexed just like python lists.

In [ ]:
# Get first 2 elements of eac dimension

rank_4_tensor[:2,:2,:2,:4]

<tf.Tensor: shape=(2, 2, 2, 4), dtype=float32, numpy=
array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#Get the firs element  from each dimension from each index expet fro the final one
rank_4_tensor[:1,:1,:1].numpy()

array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)

In [ ]:
#Create a rank 2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10,3],[2,3]])
rank_2_tensor.ndim

2

In [ ]:
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 3], dtype=int32)>

In [ ]:
#Add in tensor extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor


<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 3]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [ ]:
# Alternatice to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 3]],

       [[ 2],
        [ 3]]], dtype=int32)>

In [ ]:
# You can add values to  a tensor using the addition operator

tensor = tf.constant([[10,7],[8,90]])
tensor/10



<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.8, 9. ]])>

In [ ]:
# We can use the tennsor flow built-in function
tf.add(tensor,10)
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 80, 900]], dtype=int32)>

In [ ]:
print(tensor@tensor)
tf.matmul(tensor,tensor)


tf.Tensor(
[[ 156  700]
 [ 800 8156]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 156,  700],
       [ 800, 8156]], dtype=int32)>

In [ ]:
test_tensor=tf.constant([[1,2],[7,2],[3,3]])
test_tensor2=tf.constant([[3],[6],[8]])
tf.matmul(tf.reshape(test_tensor,shape=(2,3)),test_tensor2)


<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[71],
       [48]], dtype=int32)>

In [ ]:
# reshape tensor with transpose
test_tensor, tf.transpose(test_tensor),test_tensor2, tf.reshape(test_tensor, shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [7, 2],
        [3, 3]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 7, 3],
        [2, 2, 3]], dtype=int32)>,
 <tf.Tensor: shape=(3, 1), dtype=int32, numpy=
 array([[3],
        [6],
        [8]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 7],
        [2, 3, 3]], dtype=int32)>)

In [ ]:
#Try mtarix mult with transpose
tf.matmul(tf.transpose(test_tensor),test_tensor2)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[69],
       [42]], dtype=int32)>

In [ ]:
tf.tensordot(tf.transpose(test_tensor),test_tensor2, axes=1)

<tf.Tensor: shape=(2, 1), dtype=int32, numpy=
array([[69],
       [42]], dtype=int32)>

In [ ]:
B = tf.constant([[1.7,3.2],[1.2,5.6]])
B

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.7, 3.2],
       [1.2, 5.6]], dtype=float32)>

In [ ]:
# Change dtype of tensor
tf.cast(B,dtype=tf.float16)

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[1.7, 3.2],
       [1.2, 5.6]], dtype=float16)>

In [ ]:
C = tf.constant([[-1,-2],[3,4]])
C

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[-1, -2],
       [ 3,  4]], dtype=int32)>

### AGGREGATING tensors

In [ ]:
#Return same tensor but turn the negative int to positive
tf.abs(C)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
U = tf.constant(np.random.randint(0,100,size=50))
U

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([68, 22, 58, 78, 10, 11, 57, 54,  3, 18, 62, 15, 92, 27,  3, 16,  3,
       79, 74, 28, 98, 19, 46, 51, 15, 70, 68, 64, 36, 86, 45,  8, 18, 14,
       97, 69,  7, 96, 61, 76, 51, 96, 88, 84, 57,  0, 82, 80, 50, 10])>

In [ ]:
tf.reduce_min(tf.reshape(U,shape=(10,5)))

<tf.Tensor: shape=(), dtype=int64, numpy=0>

In [ ]:
tf.reduce_max(U)

<tf.Tensor: shape=(), dtype=int64, numpy=98>

In [ ]:
tf.reduce_mean(U)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
tf.reduce_sum(U)

<tf.Tensor: shape=(), dtype=int64, numpy=2420>

In [ ]:
tf.math.reduce_std(tf.cast(U,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=31.155737>

In [ ]:
tf.math.reduce_variance(tf.cast(U,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=970.68>

### Find the positional min ,max

In [ ]:
F = tf.random.uniform(shape=[50])
tf.reshape(F,shape=(10,5))


<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.533517  , 0.96770155, 0.6945795 , 0.5345806 , 0.7656667 ],
       [0.17176735, 0.6189555 , 0.3416686 , 0.411785  , 0.06905842],
       [0.4499563 , 0.44776237, 0.13390875, 0.80637443, 0.6515355 ],
       [0.9804231 , 0.4074248 , 0.6664448 , 0.4707713 , 0.47038424],
       [0.01349187, 0.04563463, 0.23566914, 0.9234983 , 0.94908   ],
       [0.84737265, 0.4593165 , 0.473552  , 0.04484892, 0.59660757],
       [0.55363834, 0.6295966 , 0.40924048, 0.12737226, 0.79868615],
       [0.3982358 , 0.78974056, 0.94155395, 0.6347506 , 0.6622727 ],
       [0.72235286, 0.15785778, 0.07670176, 0.05612791, 0.9999784 ],
       [0.2799611 , 0.33378303, 0.9377041 , 0.91646826, 0.1423198 ]],
      dtype=float32)>

In [ ]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=25>

In [ ]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=33>

In [ ]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9948571>

### Squeezing a tensor (removing all single dimensions)


In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1,1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686, 0.3103881 , 0.7223358 ,
            0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ,
            0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173, 0.9485276 , 0.23752594,
            0.81179297, 0.5263394 , 0.494308  , 0.21612847,
            0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]]]]]], dtype=float32)>

In [ ]:
G_squeezed= tf.squeeze(G)
G_squeezed.shape

TensorShape([50])

### One-hot encoding tensor


In [ ]:
some_list = [0,1,2,3]
#One hot encode
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot
tf.one_hot(some_list,depth=4,on_value="yo i love deep learnig", off_value="i also like to dancce")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learnig', b'i also like to dancce',
        b'i also like to dancce', b'i also like to dancce'],
       [b'i also like to dancce', b'yo i love deep learnig',
        b'i also like to dancce', b'i also like to dancce'],
       [b'i also like to dancce', b'i also like to dancce',
        b'yo i love deep learnig', b'i also like to dancce'],
       [b'i also like to dancce', b'i also like to dancce',
        b'i also like to dancce', b'yo i love deep learnig']],
      dtype=object)>

### Few common math operations

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
tf.math.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

### Tensors and NumPy

Tensor Flow interacs beautifully with array

In [ ]:
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert to numpy array
np.array(J)

array([ 3.,  7., 10.])

In [ ]:
#Convert tensor J to numpy array
J.numpy()

array([ 3.,  7., 10.])

In [ ]:
# The default type of each is slightly different
numpy_J = tf.constant(np.array([3.,7.,10.]))
tensor_J = tf.constant([3.,7.,10.])

# Check dtype
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPU

In [ ]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!nvidia-smi

Sun Nov  5 05:04:27 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   67C    P0    31W /  70W |    361MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### If you have access to CUDA-enabled GPU, TensorFlow will use it whenever possible